@startuml

left to right direction

actor "Administrador" as Admin
actor "Operador" as Operador
actor "Recepcionista" as Recepcionista
actor "Cliente" as Cliente

rectangle "Sistema de Registro\n(Clientes, Paquetes, Rutas, Ganancias)" {
    usecase "Configurar Sistema" as Configuracion
    usecase "Crear Ruta" as CrearRuta
    usecase "Desactivar Ruta" as DesactivarRuta
    usecase "Agregar Punto de Control" as AgregarPuntoControl
    usecase "Quitar Punto de Control" as QuitarPuntoControl
    usecase "Configurar Tarifa de Operación" as ConfigTarifaOperacion
    usecase "Configurar Cuota de Destino" as ConfigCuotaDestino
    usecase "Desactivar Usuario" as DesactivarUsuario
    usecase "Modificar Datos de Punto de Control" as ModificarDatosPuntoControl

    Admin --> Configuracion
    Admin --> CrearRuta
    Admin --> DesactivarRuta
    Admin --> AgregarPuntoControl
    Admin --> QuitarPuntoControl
    Admin --> ConfigTarifaOperacion
    Admin --> ConfigCuotaDestino
    Admin --> DesactivarUsuario
    Admin --> ModificarDatosPuntoControl

    usecase "Procesar Paquete" as ProcesarPaquete
    usecase "Visualizar Paquetes Pendientes" as VisualizarPaquetesPendientes
    usecase "Consultar Localización de Paquetes" as ConsultarLocalizacion

    Operador --> ProcesarPaquete
    Operador --> VisualizarPaquetesPendientes
    Operador --> ConsultarLocalizacion

    usecase "Ingresar Paquete" as IngresarPaquete
    usecase "Crear Cliente (si es necesario)" as CrearCliente

    Recepcionista --> IngresarPaquete
    Recepcionista --> CrearCliente

    usecase "Generar Factura" as GenerarFactura

    IngresarPaquete --> GenerarFactura

    usecase "Consultar Estado del Paquete" as ConsultarEstadoPaquete
    usecase "Consultar Localización del Paquete" as ConsultarLocalizacionPaquete

    Cliente --> ConsultarEstadoPaquete
    Cliente --> ConsultarLocalizacionPaquete
}

@enduml